name: Trigger auto deployment for konrad-portfolio

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/konrad-portfolio-AutoDeployTrigger-d7abde43-a460-437e-b3a4-8e0ce91da9dc.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.KONRADPORTFOLIO_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.KONRADPORTFOLIO_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.KONRADPORTFOLIO_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          dockerfilePath: Dockerfile
          registryUrl: acrkonradportfolio2024.azurecr.io
          registryUsername: ${{ secrets.KONRADPORTFOLIO_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.KONRADPORTFOLIO_REGISTRY_PASSWORD }}
          containerAppName: konrad-portfolio
          resourceGroup: rg-konrad-portfolio
          imageToBuild: acrkonradportfolio2024.azurecr.io/konrad-portfolio:${{ github.sha }}


